ges_gfct:
    resource: "@gesGfctBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
  resource: "@gesGfctBundle/Controller"
  type: annotation
  prefix: /admin/
