<?php

namespace gesGfctBundle\Repository;

/**
 * alumnos1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alumnos1Repository extends \Doctrine\ORM\EntityRepository
{
}
