<?php

namespace gesGfctBundle\Repository;

/**
 * alumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alumnoRepository extends \Doctrine\ORM\EntityRepository
{
}
