<?php

namespace gesGfctBundle\Repository;

/**
 * confRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class confRepository extends \Doctrine\ORM\EntityRepository
{
}
